### ISSUE TITLE
Identify which fields are needed for the summary statistics and if the format and values are correct.

### ISSUE THREAD

**Issue by Dior13** [rileeki-org/synthetic-database-project#33]

**Comment by rileeki** [comment]
- principal diagnosis group
- principal procedure group
- admission source (point of origin)
- admission source (route)
- admission type 
- disposition
- sex
- ethnicity
- age groups (at discharge)
- race
- patient zip code group
- expected payer source
- DNR orders
- length of stay
- type of care

**Comment by rileeki** [comment]
https://docs.google.com/spreadsheets/d/1uWe-IaOa1SV7UIm4N8fs-ym2XtGVVCDMKyDE3fL8oQ8/edit?usp=sharing
