### ISSUE TITLE
Output in Fixed Width Format

### ISSUE THREAD

**Issue by NickKramer87** [rileeki-org/synthetic-database-project#60]
As a data analyst, I want the synthetic database to output in the same format as the data that hospitals have in house so that the program I write for the synthetic data can be used on real hospital data without any modifications.

Proposed Subtasks:
1. Output the data in fixed width format.

Acceptance Criteria:
1. Synthetic data files and hospital data files should both be able to be read by a single program.

**Comment by TravisHaussler** [comment]
@iqtang wrote the draft for this and the most recent branch should finish that work and create a fixed width to the specifications
