### ISSUE TITLE
Separation of Operational Modes

### ISSUE THREAD

**Issue by NickKramer87** [rileeki-org/synthetic-database-project#71]
As a database generator, I want to have an option to generate synthetic databases before all of the formatting issues are fixed so that I can get a head start on the analysis of the databases' accuracy.

Proposed Subtasks:
1. Split the database generation and formatting into two separate functions so that they can be done independently.

Acceptance Criteria: 
1. A new version of the program where these two operations are performed separately.

**Comment by TravisHaussler** [comment]
If I am interpreting this correctly it is a simple change that can be thought of within Phase2.
I am assigning it as such and creating a quick branch to knock it out now.
